#!/bin/bash

PROJECTSDIR="$HOME/Desktop/Projects"

project=$(ls -d "$PROJECTSDIR"/*/ 2>/dev/null | xargs -n 1 basename | fzf) || exit
project_path="$PROJECTSDIR/$project"

if tmux has-session -t "$project" 2>/dev/null; then
    tmux attach-session -t "$project"
else
    tmux new-session -s "$project" -c "$project_path" "nvim ."
fi
